version: '3.9'
services:
  db:
    image: postgres:15
    container_name: fintech_postgres
    restart: unless-stopped
    env_file:
      - ./backend/app/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

